[resources]
file_icons = "src/ui/resources/Font Awesome 6 Free-Solid-900.otf"
file_database = "outomaatti.db"

[ui]
window_name = "Outomaatti"
default_universe_width = 100
default_universe_height = 100

# Tuples "(255, 255, 255)" are not supported by Dynaconf
# Please write color codes in hex strings ("#FFFFFF")

# Menu
menu_color_background = "#4EC5F1"
menu_color_background_speed = "#003AFF"
menu_color_logo_text = "#FFFFFF"
menu_color_text = "#FFFFFF"
menu_color_active_icon = "#FFFFFF"
menu_color_inactive_icon = "#808080"
menu_font_name = "Arial"
menu_font_size = 16
menu_icon_font_size = 24

# Status bar
status_color_text = "#4EC5F1"
status_font_name = "Arial"
status_font_size = 16

[rules]
